[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
log = "0.4"
env_logger = "0.9"
futures = "0.3"
chrono = "0.4"
diameter = "0.6.0"

